replicaCount: 3

image:
  repository: 04unit04/final-devops-bank-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
# NodePort must match terraform/main.tf (aws_lb_target_group.tg.port)
  type: LoadBalancer
  port: 80
  targetPort: 5000
  nodePort: 30080

nfs:
  enabled: true
  # In real deploy this IP is overridden from Ansible (k8s-app.yml) via --set nfs.server=...
  server: 10.0.0.10
   # Must match NFS export path from ansible/nfs-server.yml        
  path: /srv/nfs/bank-app
  size: 1Gi
  mountPath: /data
